/*
 * commands.h
 *
 *  Created on: Aug 5, 2019
 *      Author: Rakshit
 */

#ifndef APP_DALI_COMMANDS_H_
#define APP_DALI_COMMANDS_H_

#define BROADCAST_DP		0xFE
#define BROADCAST_C			0xFF
#define REPEAT_NUMBER		2
#define BLINK_REPEAT_NUMBER 1

enum
{

	/*
	 * 		DIRECT POWER ACCESS
	 */
	LUM_OFF,
	LUM_ON = 1,
	/*
	 * 		COMMANDS
	 */
	LUM_DOWN = 2,
	LUM_STEPUP,
	LUM_STEPDOWN,
	LUM_RECALL_MAX,
	LUM_RECALL_MIN,
	LUM_STEPDOWN_OFF,
	LUM_STEPUP_ON,
	LUM_GOTO_LAST_ACTIVE_LEV = (0x0A),
	LUM_GOTO_SCENE = (0x10),
	LUM_RESET = (0x20),
	LUM_STORE_ACT_LEVEL,

	LUM_IDENTIFY = (0x25),
	LUM_STORE_MAX_LEVEL = (0x2A),
	LUM_STORE_MIN_LEVEL,
	LUM_STORE_SYS_FAIL,
	LUM_STORE_POWON_LEVEL,
	LUM_STORE_FADE_TIME,
	LUM_STORE_FADE_RATE,

	LUM_STORE_SCENE = (0x40),
	LUM_REMOVE_SCENE = (0x50),
	LUM_ADD_TO_GROUP = (0x60),
	LUM_REMOVE_FROM_GROUP = (0x70),
	LUM_STORE_SHORTADD,
	/*
	 * 		QUERY COMMANDS
	 */
	LUM_QSTATUS = (0x90),
	LUM_QCGEAR,
	LUM_QLAMP_FAIL,
	LUM_QLAMP_ON,
	LUM_QLIMIT_ERROR,
	LUM_QRESET_STATE,
	LUM_QMISSING_SHORTADD,
	LUM_QVERSION,
	LUM_QDTR,
	LUM_QDEVICE_TYPE = (0x99),
	LUM_QPHY_MINLEVEL,
	LUM_QPOW_FAIL,
	LUM_QDTR1 = (0x9C),
	LUM_QDTR2 = (0x9D),

	LUM_QCUR_LEVEL = 0xA0,
	LUM_QMAX_LEVEL = 0xA1,
	LUM_QMIN_LEVEL = 0xA2,
	LUM_QPOW_ON_LEVEL = 0xA3,
	LUM_QSYS_FAIL_LEVEL = 0xA4,
	LUM_QSYS_FADE_TIME_RATE = 0xA5,

	LUM_QGRP_0_7 = (0xC0),
	LUM_QGRP_7_15 = (0xC1),

	LUM_QRAND_ADD_H = (0xC2),
	LUM_QRAND_ADD_M,
	LUM_QRAND_ADD_L,

	LUM_ACTIVATE = (0xE2),
	LUM_SET_TEMP_TC = (0xE7),
	LUM_SET_TC_WARM = (0xE9),
	LUM_COPY_REP_TEMP = (0xEE),

	LUM_STORE_GEAR_FEATURES = (0xF3),
	LUM_QGEAR_FEATURES = (0xF7),
	LUM_QCOLOUR_STAT = (0xF8),
	LUM_QCOL_TYPE = (0xF9),
	LUM_QCOLOUR_VAL = (0xFA),
	/*
	 * 		SPECIAL COMMANDS
	 */
	LUM_SP_TERMINATE = (0xA1),
	LUM_SP_DTR = (0xA3),
	LUM_SP_INITIALIZE_ADDRESSING = (0xA5),
	LUM_SP_RANDOMIZE = (0xA7),
	LUM_SP_COMPARE = (0xA9),
	LUM_SP_WITHDRAW = (0xAB),
	LUM_SP_SEARCH_ADDH = (0xB1),
	LUM_SP_SEARCH_ADDM = (0xB3),
	LUM_SP_SEARCH_ADDL = (0xB5),
	LUM_SP_PROGRAM_SADD = (0xB7),
	LUM_SP_VERIFY_SADD = (0xB9),
	LUM_SP_QSADD = (0xBB),

	/*
	 * 		EXTENDED COMMANDS
	 */
	LUM_DIMMING_CV = (0xE3)

};

enum
{
	/*
	 * 		EXTENDED SPECIAL COMMANDS
	 */
	LUM_ESP_EN_DT = (0xC1), LUM_ESP_DTR1 = (0xC3), LUM_ESP_DTR2 = (0xC5),

};

enum
{
	COMMAND_INIT_STATE,
	COMMAND_EXECUTION_STATE,
	COMPLETION_STATE,
	RESPONSE_STATE,
	REPEAT_STATE,
	WAIT_STATE1,
	WAIT_STATE2,
};

enum
{
	TERMINATE_STATE,
	QUERY_BALLAST_RESET,
	INIT_ADDRESSING_WINDOW,
	RANDOMIZE,
	INPUT_ADDRESS,
	SEARCH_ADDRESS,
	COMPARE_ADDRESS,
	PROGRAM_SHORT_ADDRESS,
	WITHDRAW_MATCHED_ADDRESS,
	INDENTIFY_LUMINARY,
	PROGRAM_SADD_TO_DTR,
	QUERY_DTR0,
	STORE_DTR_AS_SHORTADD,
	QUERY_SHORTADD,
	VERIFY_SHORTADD,
	SET_FADE_TIME,
	QUERY_RDM_ADD,
	DALI_COM_WAIT_STATE,
	QUERY_BALLASTINFO,
};

enum
{
	SEARCH_ENGINE_ESTABLISHMENT, COMPARISION, NO_MATCHING_ADDRESS,
};

enum
{
	INLOOP_FIRST_ITN,
	INLOOP_FIRST_ITN_ADDRESS_CONFIRMATION,
	INLOOP_SECOND_ITN,
	INLOOP_SECOND_ITN_ADDRESS_CONFIRMATION,
	INLOOP_END_COMPARISION
};
#endif /* DALICOMMANDS_H_ */
